### ISSUE TITLE
Google Images' HTTP requests aren't using network proxy

### ISSUE THREAD

**Issue by JiaChen-Zeng** [migaku-official/Migaku-Dictionary-Addon#16]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Win 10

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
Google Images always shows "Loading..." and then "No Images Found. This is likely due to a connectivity error." I am in a region where Google's services are blocked, so I am using a system-wide global HTTP proxy. However, it seems that it doesn't send requests via the proxy.

Here are some other Anki add-ons that can make requests via the proxy. Hope it helps.
- https://github.com/AwesomeTTS/awesometts-anki-addon
- https://github.com/ssricardo/anki-plugins/tree/master/anki-web-browser

**Comment by LucasMIA** [comment]
Proxies already work with the add-on, I regularly use them as well. The issue with Google Images happened last week and was fixed last Wednesday. Please make sure you up to date and follow the updating procedure from the AnkiWeb page: 

Updating Instructions
In order to update this add-on, it must first be disabled and then Anki must be restarted. Then you may check for updates, update and re-enable the add-on and then restart Anki.

https://ankiweb.net/shared/info/1655992655

**Comment by LucasMIA** [comment]
Report back when you've done so, so that I may close this issue.

**Comment by JiaChen-Zeng** [comment]
Thank you for your fast response.
Indeed I was using the old version. After updating, it works in global mode but doesn't in PAC mode. Though I am fine with it now.

**Comment by LucasMIA** [comment]
It works with standard vpn applications, if you want to use it with something else, then you will have to configure it.
