### ISSUE TITLE
Navigation Hotkey Support

### ISSUE THREAD

**Issue by miya-sans** [migaku-official/Migaku-Dictionary-Addon#23]
**Type:**
  - [ ] bug
  - [x] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Windows 10

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**

Currently the addon is lacking in navigation hotkey support. I propose adopting conventions from [GoldenDict](https://github.com/goldendict/goldendict/wiki/Useful-Shortcuts) and most [web browers](https://www.howtogeek.com/114518/47-keyboard-shortcuts-that-work-in-all-web-browsers/). Ordered from most to least used. Preferred hotkey when alternatives are present are listed first. Alternatives are listed for the purpose of popular convention. 

- Focus on search bar: Ctrl+L or Alt+D
- Next / previous tab: Ctrl+Page Down or Ctrl+Tab / Ctrl+Page Up or Ctrl+Shift+Tab 
- Next / previous history: Alt+Right / Alt+Left
- Open a new tab: Ctrl+T
- Close current tab: Ctrl+W (this is already used as a hotkey for opening the dictionary) or Ctrl+F4 
- Reopen the last closed tab: Ctrl+Shift+T
- Jump to the next / previous dictionary in the results: Alt+Down / Alt+Up
- Switch to the specified tab, counting from the left: Ctrl+1-8
- Switch to the last tab: Ctrl+9 
- Zoom in / Zoom out: Ctrl+= or Ctrl+Mousewheel Up / Ctrl+- or Ctrl+Mousewheel Down

**Comment by KieranBrannigan** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
