### ISSUE TITLE
"Export Definitions" operation should remember selected options

### ISSUE THREAD

**Issue by ercanserteli** [migaku-official/Migaku-Dictionary-Addon#24]
**Type:**
  - [ ] bug
  - [ ] feature
  - [x] enhancement
  - [ ] question

**Environment:**
  - OS: Windows

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
As someome using this addon together with MorphMan, I have to perform a ritual every day after finishing my reps and running MorphMan recalc where I need to generate meanings for cards that just turned into 1T (got a focus morph). Using a saved filter in the browser, selecting the new 1T cards is easy enough. However, using the Export Definitions functionality, I have to set the same options every single time I run it. It would be very useful if the addon remembered the options I chose the last time. 

Check this video to see what I am talking about:
[https://www.youtube.com/watch?v=JTpqnb52FLc](url)

All in all, I counted 13 precise mouse clicks. Sometimes there will be new cards with meaningless focus morphs (like in the video) where I need to set "already known" and recalc again, which means I need to perform the steps again until there are no new 1T cards.

**Comment by KieranBrannigan** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
