### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by dmgerman** [migaku-official/Migaku-Dictionary-Addon#25]
**Type:**
  - [ ] bug
  - [ ] feature
  - [ x] enhancement
  - [ ] question

**Environment:**
  - OS:

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x ] no

**Description:**
[ Write the issue description here ]

I noticed you  you have added a version number. This is great. It would be beneficial to have a changelog that enumerates the major changes between versions. thank you

**Comment by KieranBrannigan** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
