### ISSUE TITLE
Custom Shortcuts

### ISSUE THREAD

**Issue by matehuos** [migaku-official/Migaku-Dictionary-Addon#26]
**Type:**
  - [ ] bug
  - [ ] feature
  - [ X] enhancement
  - [ ] question

**Environment:**
  - OS: Windows 10

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [ X] no

**Description:**
Hello guys, is there a way to add custom shortcuts in a new build or to change it in the current one.
Thanks!

**Comment by KieranBrannigan** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
