### ISSUE TITLE
Capitalized Esperanto Characters are Case Sensitive

### ISSUE THREAD

**Issue by msocca** [migaku-official/Migaku-Dictionary-Addon#29]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Windows 10

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
When searching for Esperanto words in the dictionary, non-latin Esperanto characters are treated as case sensitive.

Characters effected:
ĈĜĤĴŜŬ
ĉĝĥĵŝŭ

**Comment by p2635** [comment]
I assume you somehow got your hands on an esperanto dictionary for Migaku, can you point me to it?

I had a look at the mega.nz link but it's not there. If it's usable, it might be worth sharing with the Esperanto reddit so they know it exists.

**Comment by KieranBrannigan** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
