### ISSUE TITLE
Disable Image Upscaling

### ISSUE THREAD

**Issue by msocca** [migaku-official/Migaku-Dictionary-Addon#30]
**Type:**
  - [ ] bug
  - [ ] feature
  - [x] enhancement
  - [ ] question

**Environment:**
  - OS: Windows 10

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
When pasting an image into the exporter, or picking out an image from google images, if the image being pasted is smaller than the maximum width or height, the image gets upscaled. This adds extra size to cards and adds blur to small images.

Example, a small image being upscaled to fit the minimum/maximum of 300x300:
![無題2](https://user-images.githubusercontent.com/65642777/82516868-5585d080-9b0b-11ea-8304-f9288949d6eb.png)
![無題3](https://user-images.githubusercontent.com/65642777/82516887-5d457500-9b0b-11ea-9ef8-ff2f20feb413.png)

**Comment by KieranBrannigan** [comment]
We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
