### ISSUE TITLE
Bug on win 7 64bit

### ISSUE THREAD

**Issue by HoanPiTa** [migaku-official/Migaku-Dictionary-Addon#33]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS:

**I'm going to open a PR to resolve the issue:**
  - [ v] yes
  - [ ] no

Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 7
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-06-07 13:17:34

Caught exception:
Traceback (most recent call last):
  File "C:\Users\laptop88\AppData\Roaming\Anki2\addons21\1655992655\main.py", line 523, in openDictionarySettings
    mw.dictSettings = SettingsGui(mw, addon_path, openDictionarySettings)
  File "C:\Users\laptop88\AppData\Roaming\Anki2\addons21\1655992655\addonSettings.py", line 92, in __init__
    self.userGuideTab = self.getUserGuideTab()
  File "C:\Users\laptop88\AppData\Roaming\Anki2\addons21\1655992655\addonSettings.py", line 544, in getUserGuideTab
    guide._page.setHtml(html, url)
TypeError: setHtmlWithBaseurl() takes 2 positional arguments but 3 were given

**Comment by KieranBrannigan** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
