### ISSUE TITLE
DB insertion is slow

### ISSUE THREAD

**Issue by izik1** [migaku-official/Migaku-Dictionary-Addon#4]
**Type:**
  - [ ] bug
  - [ ] feature
  - [x] enhancement
  - [ ] question

**Environment:**
  - OS: Any (but Arch Linux/KDE)

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
I recognize that this is probably not a huge priority.

DB insertion for words inserts a single word at a time, this is _very_ slow as DB calls are expensive even in SQLite. It would be better to batch word insertion.

What you do is change https://github.com/mass-immersion-approach/MIA-Dictionary-Addon/blob/21169885ce98bbf8674a8298d6303248d5f15c20/src/dictdb.py#L350 to use `executemany` and an array instead of a single item at a time. (see https://stackoverflow.com/a/32239587)

**Comment by grenzionky** [comment]
another reason why its so slow, is because it prints out the change in words in the popup, and printing takes a **ton** of time. If it would instead only print every 
thousandths or even ten thousandths word, it would immensely speed it up.

also, why not download the entire dictionary as the database file to begin with, instead of downloading the jsons first only to have the script gather it into a sql database? 

maybe u can make the pull request since you already solved a part of it

**Comment by izik1** [comment]
It does actually only print every so often, even though it sets the label, it doesn't seem to actually change the pop up (I only ever see multiples of whatever number they set, can't remember off the top of my head)

**Comment by LucasMIA** [comment]
Hey guys, good idea, I didn't touch that part of the code in ages and didn't even think to take a look at optimizing it. I will do this coming up here once I get a chance after the holidays~~. Hope you guys are enjoying your holidays as well!
