### ISSUE TITLE
Card Exporter: (Ctrl + Shift + v) shortcut not being recognized by captureKey@main.py 

### ISSUE THREAD

**Issue by marcuscastelo** [migaku-official/Migaku-Dictionary-Addon#41]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Arch Linux
  - DE: KDE Plasma 5.19.4
  - Clibboard tool: xsel (xclip not installed)

**I'm going to open a PR to resolve the issue:**
  - [x] yes
  - [ ] no

**Description:**
Symptom: unable to paste image and/or audio to CardExporter
Problem: in my environment, pressing Ctrl + Shift + v doesn't trigger captureKey's elif @main.py
Solution: change shotcut to Ctrl + Shift + V (caps V)

It' a really trivial bug, literally one line to fix it.

https://github.com/mass-immersion-approach/MIA-Dictionary-Addon/blob/48c2aebeb0e42dd36414ebb911c3c0cf83916f5a/src/main.py#L470

My particular solution:

```py
elif 'Key.ctrl' in mw.currentlyPressed and 'Key.shift' in mw.currentlyPressed and ("'V'" in mw.currentlyPressed or "'v'" in mw.currentlyPressed):
```
I've left both 'V' and 'v' in my setup since I thought it was capitalized because of shift modifier, but testing with caps on doesn't seem to change anything, it stays 'V'. But i left it anyway since other systems may have the lowercase 'v'.
![Uppercase and lowercase behavior](https://user-images.githubusercontent.com/27441558/91146144-dd402580-e68c-11ea-8bfd-b0084670090a.gif)

**Comment by KieranBrannigan** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
