### ISSUE TITLE
Add button to purge database file

### ISSUE THREAD

**Issue by mainrs** [migaku-official/Migaku-Dictionary-Addon#45]
**Type:**
  - [ ] bug
  - [ ] feature
  - [x] enhancement
  - [ ] question

**I'm going to open a PR to resolve the issue:**
  - [x] yes (if you help me out on it, first Anki addon I'd contribute to :) )
  - [ ] no

**Description:**
I had some trouble installing the dictionaries. Not sure what went wrong, but Anki kept removing one of them constantly. I've deleted the database file with the hope that that would force the addon to re-import everything. But that wasn't actually the case. I got an error as it couldn't find the database file.

Would it be possible to somehow add a simple button that just drops all tables and creates them again? Basically deleting all data inside of them?

**Comment by KieranBrannigan** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
