### ISSUE TITLE
Searching using Cyrillic characters for Russian appears to be case-sensitive

### ISSUE THREAD

**Issue by Adaminius** [migaku-official/Migaku-Dictionary-Addon#47]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Windows
  - Addon version 1.1.03

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
Searching using the Russian-English dictionary (which uses Cyrillic characters) returns no results if the query is capitalized.

**Comment by Adaminius** [comment]
Also, the included dictionary seems to have the "ё"s as "е". Writing "ё" this way is common in conversational text because it's a rarer letter, but it makes it impossible to look up words with that letter in them when they are spelled properly. I think the best solution would be to run a second search with "е" substituted for "ё" and to use a dictionary with the correct spelling of words. Someone who's never seen the word before will not know if a "е" is supposed to be a "ё", and they are pronounced completely differently.

**Comment by KieranBrannigan** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
