### ISSUE TITLE
search both kanas simultaneously

### ISSUE THREAD

**Issue by grenzionky** [migaku-official/Migaku-Dictionary-Addon#5]
**Type:**
  - [ ] bug
  - [ ] feature
  - [X] enhancement
  - [ ] question

**Environment:**
  - OS: any (Linux/AwesomeWM)

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [X] no

**Description:**
I have the MIA Japanese addon set to convert all kana to katakana, but now when i select a word (lets say 来ル) and press ctrl+s, it never finds the words cuz the dictionary is expecting hiragana (来る), so can you make a system where if it doesn't find results from the kana that got searched, it should automatically convert it to the other kana so that it will find the words, cuz as of now, with convert-to-katakana on, the dictionary addon is unusable in Japanese

**Comment by LucasMIA** [comment]
Interesting idea, I can revisit it in the future after I finish the current plans.

**Comment by KieranBrannigan** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
